---
title: "C9orf72 mice - olfaction task - old time point"
output: html_document
date: "2025-02-05"
---

***Load libraries and data***

```{r}
library(readr)
library(forcats)
library(lme4)
library(ggplot2)
library(lmerTest)
library(emmeans)
library(ggResidpanel)
library(car)
library(plyr)
library(dplyr)
library(stringr)

#Set path to working directory
setwd("~/Downloads/ML-analysis-olfaction/Figure5")

#Read data 
data_mouse <- read_csv("filtered_manvsML_C9_67Weeks_gen_corr_filtered.csv", col_types = cols (
  Video_id = 'f',
  Odour_presentation = 'f',
  Source='f',
  Sex = 'f',
  Odour_type_presentation = 'f',
  Genotype = 'f'
))

data_mouse$Odour_presentationordered <- ordered(data_mouse$Odour_presentation, levels=c("Odour1.1", "Odour1.2", "Odour1.3", "Odour2.1", "Odour2.2", "Odour2.3","Odour3.1", "Odour3.2", "Odour3.3"))
data_mouse$Sourceordered <- ordered(data_mouse$Source, levels=c("Manual", "ML"))


data_mouse$Genotypeordered <- ordered(data_mouse$Genotype, levels=c("4", "2"))
data_mouse$Odour_type_presentationordered <- ordered(data_mouse$Odour_type_presentation, levels=c("Water1", "Water2", "Water3", "Familiar1","Familiar2", "Familiar3","Novel1", "Novel2", "Novel3"))

table1::label(data_mouse$Video_id) <- "Video_id"
table1::label(data_mouse$Genotypeordered) <- "Genotype"
table1::label(data_mouse$Odour_presentationordered) <- "Odour_presentation"
table1::label(data_mouse$Odour_type_presentationordered) <- "Odour_type_presentation"

table1::table1(~  Video_id|Odour_presentationordered, data = data_mouse)
table1::table1(~  Odour_presentation|Genotypeordered, data = data_mouse)
table1::table1(~  Odour_type_presentation|Genotypeordered, data = data_mouse)
```

***Stats***
```{r}
#relevel the data to compare everything in the model to control mice
data_mouse$Genotype <- relevel(data_mouse$Genotype, ref = "4")

#linear mixed effects model 
ME_EXPL<- lmer(Duration_sniffing~Source*Genotype*(Sex+Odour_type_presentation) + (1|Video_id),data = data_mouse)
summary(ME_EXPL)
resid_panel(ME_EXPL)
anova(ME_EXPL, type=3)

#post-hoc exploring odour type presentation at every genotype and source
emmeans(ME_EXPL, list(pairwise ~ Odour_type_presentation|Genotype|Source), adjust = "bonferroni")

#post-hoc exploring genotype at every odour type presentation
emm1 <- emmeans(ME_EXPL, ~Genotype*Odour_type_presentation|Source)
str(emm1)
coef_t_freq1 <- coef(pairs(emm1))
custom_contrasts1 <- list("w1 4 vs 2" = c(1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                         "w2 4 vs 2" = c(0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                         "w3 4 vs 2" = c(0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                         "f1 4 vs 2" = c(0, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
                         "f2 4 vs 2" = c(0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0, 0),
                         "f3 4 vs 2" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0),
                         "n1 4 vs 2" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0),
                         "n2 4 vs 2" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0),
                         "n3 4 vs 2" = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1))
specific_comparisons1 <-contrast(emm1, custom_contrasts1)
summary_comparisons1 <- summary(specific_comparisons1, adjust="bonferroni")
print(summary_comparisons1)


```

***Plot by genotype and source***
```{r}
# Aggregate data based on odour type presentation, genotype, and source
EXPL_Gen_Source <- ddply(data_mouse, c("Odour_type_presentationordered", "Genotypeordered", "Source"), summarise,
                   N    = length(Duration_sniffing),
                   mean = mean(Duration_sniffing, na.rm = TRUE),
                   sd   = sd(Duration_sniffing, na.rm = TRUE),
                   se   = sd / sqrt(N))

# Plot genotype by color, source by line type
pEXPL_Gen_Source <- ggplot(EXPL_Gen_Source, aes(
  x = Odour_type_presentationordered, 
  y = mean, 
  group = interaction(Genotypeordered, Source), 
  colour = Genotypeordered,  # Genotype by color
  linetype = Source  # Sex by line type
)) +
  geom_point(size=0.6) + 
  geom_line(linewidth=0.6) + 
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2, linewidth=0.2) +
  ylab("Time sniffing (s)") + 
  xlab("Odour Presentation Manual and ML (filtered)") + 
  scale_y_continuous(breaks = seq(0, 60, by = 15), limits = c(0, 60), expand = c(0, 0)) +  
  theme_classic(base_size = 8) +
  theme(
    text = element_text(family = "Arial"),
    legend.position = "top",  # Change legend position for better visibility
    legend.direction = "horizontal",
    legend.text.align = 0,
    legend.spacing = unit(0, "cm"), 
    legend.key.height = unit(0, "cm"),  
    legend.text = element_text(size = 8, family = "Arial"), 
    legend.title = element_text(size = 8, face="bold", family = "Arial"), 
    axis.title.x = element_text(size = 8, face="bold", family = "Arial"), 
    axis.title.y = element_text(size = 8, face="bold", family = "Arial"), 
    axis.text.x = element_text(size = 8, colour="black", family = "Arial"), 
    axis.text.y = element_text(size = 8, colour="black", family = "Arial"),
    legend.background = element_rect(fill = NA, colour = NA)
  ) +
  scale_colour_manual(
    name = "67 weeks",  # Legend title for genotype
    breaks = c("4", "2"),
    labels = c("WT", expression(italic("C9orf72")^italic("GR400/+"))), # Sets the labels of items in the legend
    values = c("#009E73", "#332288")
  ) +
  scale_linetype_manual(
    name = NULL,  # Legend title for sex
    breaks = c("Manual", "ML"),
    labels = c("Manual", "ML"), # Sets the labels of items in the legend
    values = c("solid", "dashed")  # female = solid, male = dashed
  )+
     guides(colour = guide_legend(order=1), linetype = guide_legend(order =2))


# Save the plot
ggsave("ManvsML_C9_67weeks_filtered_gen.tiff", plot = pEXPL_Gen_Source, width = 5, height = 3, dpi = 300) # Adjust height, width, dpi

# Display the plot
pEXPL_Gen_Source

```

