---
title: "Untitled"
output: html_document
date: "2025-10-13"
---

```{r setup, include=FALSE}
library(ggplot2)
library(readr)
library(dplyr)

#this is a test
setwd("~/Downloads/ML-analysis-olfaction/Figure4")

# read in data 
data_mouse_C9 <- read_csv("C9_all.csv")

data_mouse_TDP43 <- read_csv("TDP_all.csv")


```

##Plots - C9
```{r pressure, echo=FALSE}

ggplot(data_mouse_C9, aes(x = Filtered, fill = Source)) +
  geom_bar(stat = "count", position = position_dodge(width = 0.9)) +
  facet_wrap(~ Age, ncol = 2) +   scale_fill_manual(values = c("#66CDAA", "#8279D6"), labels = c("Manual","ML"))+
    ggtitle(expression("WT and " * italic("C9orf72")^italic("GR400/+") * "mice"))


  theme_minimal()

ggsave("C9_hist.tiff")  # Adjust width, height, and dpi as needed and save as an image in the folder where the code file is
```


##Plots - Tdp43
```{r pressure, echo=FALSE}

ggplot(data_mouse_TDP43, aes(x = Filtered, fill = Source)) +
  geom_bar(stat = "count", position = position_dodge(width = 0.9)) +
  facet_wrap(~ Age, ncol = 2) + scale_fill_manual(values = c("#FFB366", "#80DFFF"), labels = c("Manual","ML")) + 
  
      ggtitle(expression("WT and " * italic("Tardbp")^italic("Q331K/Q331K") * "mice"))

  theme_minimal()

ggsave("TDP43_hist.tiff")  # Adjust width, height, and dpi as needed and save as an image in the folder where the code file is


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.










```{r}
library(car)
library(DHARMa)
library(lmerTest)
library(emmeans)

# read in data 
data_mouse <- read_csv("C9_nonfiltered_status.csv", col_types = cols (
  mouse_id = 'f',
  Odour_presentation = 'f',
  Sex = 'f',
  Source = 'f',
  Genotype = 'f',
  Odour_type_presentation = 'f'
))


#relevel the data to compare everything in the model to control mice
data_mouse$Source <- relevel(data_mouse$Source, ref = "Manual")


#linear mixed effects model 
ME_EXPL<- glmer(Status~ Source*Age + (1|mouse_id),data = data_mouse, family = binomial)
summary(ME_EXPL)
car::Anova(ME_EXPL, type = "III", test.statistic = "Chisq")
#post-hoc exploring olfactory habituation-dishabituation
#smell/ habituation comparison by genotype
#emmeans(ME_EXPL, list(pairwise ~ Source*Age), adjust = "bonferroni")

# DHARMa diagnostics
sim_res <- simulateResiduals(ME_EXPL, n = 1000)
plot(sim_res)

# Additional diagnostics
testDispersion(sim_res)
testZeroInflation(sim_res)
testUniformity(sim_res)




```



```{r}

library(car)
library(DHARMa)
library(lmerTest)
library(emmeans)

# read in data 
data_mouse <- read_csv("TDP_nonfiltered_status.csv", col_types = cols (
  mouse_id = 'f',
  Age = 'f',
  Odour_presentation = 'f',
  Sex = 'f',
  Source = 'f',
  Genotype = 'f',
  Odour_type_presentation = 'f'
))

#relevel the data to compare everything in the model to control mice
data_mouse$Source <- relevel(data_mouse$Source, ref = "Manual")


#linear mixed effects model 
ME_EXPL<- glmer(Status~ Source*Age + (1|mouse_id),data = data_mouse, family = binomial)
summary(ME_EXPL)
car::Anova(ME_EXPL, type = "III", test.statistic = "Chisq")

# DHARMa diagnostics
sim_res <- simulateResiduals(ME_EXPL, n = 1000)
plot(sim_res)

# Additional diagnostics
testDispersion(sim_res)
testZeroInflation(sim_res)
testUniformity(sim_res)

#post-hoc exploring olfactory habituation-dishabituation
#smell/ habituation comparison by genotype
emm <- emmeans(ME_EXPL, ~Source*Age)
str(emm)
coef_t_freq <- coef(pairs(emm))
custom_contrasts <- list("Man vs ML 15" = c(1, -1, 0, 0),
                         "Man vs ML 67" = c(0, 0, 1, -1)
                         )
specific_comparisons <-contrast(emm, custom_contrasts)
summary_comparisons <- summary(specific_comparisons, adjust="bonferroni")
print(summary_comparisons)




```